// lib/gamesList.js

export const getGamesList = (t) => [
  {
    id: 'minecraft',
    name: 'Minecraft',
    edition: t('games.minecraft.edition', 'Java & Bedrock Edition'),
    description: t('games.minecraft.desc', 'Instantly deploy high-performance servers with full plugin and modpack support.'),
    longDescription: t('games.minecraft.long_desc', 'Experience Minecraft hosting without limits. Whether you are running a lightweight vanilla server for friends or a massive BungeeCord network with 200+ mods, our NVMe storage and dedicated CPUs ensure zero tick-lag and lightning-fast chunk generation.'),
    image: '/games/minecraft-bg.jpg',
    accent: 'text-green-400',
    btnBg: 'bg-green-500',
    btnHover: 'hover:bg-green-600',
    engine: 'Java / Bedrock'
  },
  {
    id: 'satisfactory',
    name: 'Satisfactory',
    edition: t('games.satisfactory.edition', '1.0 Dedicated Servers'),
    description: t('games.satisfactory.desc', 'Build massive factories without lag. Optimized for continuous background processing.'),
    longDescription: t('games.satisfactory.long_desc', 'The factory must grow. Host your Satisfactory 1.0 dedicated server on hardware built for heavy logistics. Our servers stay online 24/7, meaning your factory keeps producing resources even while you sleep.'),
    image: '/games/satisfactory-bg.jpg',
    accent: 'text-orange-400',
    btnBg: 'bg-orange-500',
    btnHover: 'hover:bg-orange-600',
    engine: 'Unreal Engine 5'
  },
  {
    id: 'rust',
    name: 'Rust',
    edition: t('games.rust.edition', 'Vanilla & Modded'),
    description: t('games.rust.desc', 'Survive the wipe with extreme NVMe performance for seamless monument loading.'),
    longDescription: t('games.rust.long_desc', 'Rust servers require incredible single-core performance. Our fleet delivers exactly that, preventing rubber-banding during intense PvP firefights. Includes seamless 1-click Oxide/uMod installation.'),
    image: '/games/rust-bg.jpg',
    accent: 'text-red-500',
    btnBg: 'bg-red-600',
    btnHover: 'hover:bg-red-700',
    engine: 'Unity'
  },
  {
    id: 'palworld',
    name: 'Palworld',
    edition: t('games.palworld.edition', 'Dedicated Server'),
    description: t('games.palworld.desc', 'Capture, battle, and build with friends on high-performance infrastructure.'),
    longDescription: t('games.palworld.long_desc', 'Host your own Palworld dedicated server. Tame Pals, build massive bases, and explore a vast open world with up to 32 players. Our servers are optimized for high memory allocation to prevent memory leaks.'),
    image: '/games/palworld-bg.jpg',
    accent: 'text-amber-400',
    btnBg: 'bg-amber-500',
    btnHover: 'hover:bg-amber-600',
    engine: 'Unreal Engine 5'
  },
  {
    id: 'valheim',
    name: 'Valheim',
    edition: t('games.valheim.edition', 'Vanilla & Modded'),
    description: t('games.valheim.desc', 'Explore the tenth world with seamless Viking survival hosting and BepInEx support.'),
    longDescription: t('games.valheim.long_desc', 'Conquer the mythical realm of Valheim with friends. We provide robust hosting with easy crossplay support, instant backups, and manual BepInEx mod injection.'),
    image: '/games/valheim-bg.jpg',
    accent: 'text-cyan-400',
    btnBg: 'bg-cyan-600',
    btnHover: 'hover:bg-cyan-700',
    engine: 'Unity'
  },
  {
    id: 'ark_sa',
    name: 'ARK: Survival Ascended',
    edition: t('games.ark_sa.edition', 'Unreal Engine 5 Server'),
    description: t('games.ark_sa.desc', 'Dinosaur survival reimagined. Hosted on extreme NVMe drives for fast loading.'),
    longDescription: t('games.ark_sa.long_desc', 'Survive the definitive ARK experience. Built on Unreal Engine 5, ARK: SA requires serious hardware. Our premium tiers provide the heavy-duty RAM and CPU needed for smooth dino-taming.'),
    image: '/games/ark_sa-bg.jpg',
    accent: 'text-emerald-400',
    btnBg: 'bg-emerald-600',
    btnHover: 'hover:bg-emerald-700',
    engine: 'Unreal Engine 5'
  },
  {
    id: 'ark_se',
    name: 'ARK: Survival Evolved',
    edition: t('games.ark_se.edition', 'Classic Cluster Support'),
    description: t('games.ark_se.desc', 'The classic survival experience. Ready for massive mod lists and custom maps.'),
    longDescription: t('games.ark_se.long_desc', 'Host classic ARK: Survival Evolved. Perfect for massive mod lists, custom maps, and large tribes looking to dominate the Island.'),
    image: '/games/ark_se-bg.jpg',
    accent: 'text-teal-400',
    btnBg: 'bg-teal-600',
    btnHover: 'hover:bg-teal-700',
    engine: 'Unreal Engine 4'
  },
  {
    id: 'factorio',
    name: 'Factorio',
    edition: t('games.factorio.edition', 'Headless Server'),
    description: t('games.factorio.desc', 'The factory must grow. Enjoy perfectly synchronized, lag-free automation.'),
    longDescription: t('games.factorio.long_desc', 'Host a Factorio headless server. Manage sprawling logistics networks and infinite automation lines without dropping a single UPS. Perfect for massive megabases.'),
    image: '/games/factorio-bg.jpg',
    accent: 'text-yellow-500',
    btnBg: 'bg-yellow-600',
    btnHover: 'hover:bg-yellow-700',
    engine: 'Custom 2D Engine'
  },
  {
    id: 'project_zomboid',
    name: 'Project Zomboid',
    edition: t('games.project_zomboid.edition', 'Multiplayer Survival'),
    description: t('games.project_zomboid.desc', 'This is how you died. Massive, seamless multiplayer zombie survival hosting.'),
    longDescription: t('games.project_zomboid.long_desc', 'Survive Knox Country with your friends. Our servers handle vast zombie hordes, complex mod lists, and persistent chunk loading flawlessly.'),
    image: '/games/project_zomboid-bg.jpg',
    accent: 'text-rose-500',
    btnBg: 'bg-rose-600',
    btnHover: 'hover:bg-rose-700',
    engine: 'LWJGL (Java)'
  },
  {
    id: 'gmod',
    name: 'Garry\'s Mod',
    edition: t('games.gmod.edition', 'Source Engine'),
    description: t('games.gmod.desc', 'Limitless sandbox fun with instant Steam Workshop integration and fastDL.'),
    longDescription: t('games.gmod.long_desc', 'Host TTT, DarkRP, or Sandbox. Features 1-click Steam Workshop integration so your server downloads addons and mounts them instantly.'),
    image: '/games/gmod-bg.jpg',
    accent: 'text-sky-400',
    btnBg: 'bg-sky-500',
    btnHover: 'hover:bg-sky-600',
    engine: 'Source'
  },
  {
    id: 'cs2',
    name: 'Counter-Strike 2',
    edition: t('games.cs2.edition', 'Competitive Matchmaking'),
    description: t('games.cs2.desc', 'Sub-tick precision hosting for the ultimate competitive edge and community servers.'),
    longDescription: t('games.cs2.long_desc', 'Experience the new era of Counter-Strike. Our high-frequency CPUs ensure Source 2’s sub-tick architecture performs exactly as intended for community servers and scrims.'),
    image: '/games/cs2-bg.jpg',
    accent: 'text-yellow-400',
    btnBg: 'bg-yellow-500',
    btnHover: 'hover:bg-yellow-600',
    engine: 'Source 2'
  },
  {
    id: 'arma3',
    name: 'Arma 3',
    edition: t('games.arma3.edition', 'Milsim Sandbox'),
    description: t('games.arma3.desc', 'Massive military simulation with heavy Workshop mod support and reliable performance.'),
    longDescription: t('games.arma3.long_desc', 'Deploy massive combined-arms operations. Our Arma 3 servers automatically parse and mount your Steam Workshop collections, copying keys securely to the root folder.'),
    image: '/games/arma3-bg.jpg',
    accent: 'text-lime-500',
    btnBg: 'bg-lime-600',
    btnHover: 'hover:bg-lime-700',
    engine: 'Real Virtuality 4'
  },
  {
    id: 'arma_reforger',
    name: 'Arma Reforger',
    edition: t('games.arma_reforger.edition', 'Enfusion Engine'),
    description: t('games.arma_reforger.desc', 'Next-gen military simulation hosting with powerful native modding tools.'),
    longDescription: t('games.arma_reforger.long_desc', 'Experience the Enfusion engine. Arma Reforger hosting offers built-in mod management and crossplay support for PC and Xbox players.'),
    image: '/games/arma_reforger-bg.jpg',
    accent: 'text-slate-400',
    btnBg: 'bg-slate-500',
    btnHover: 'hover:bg-slate-600',
    engine: 'Enfusion'
  },
  {
    id: 'space_engineers',
    name: 'Space Engineers',
    edition: t('games.space_engineers.edition', 'Dedicated Server'),
    description: t('games.space_engineers.desc', 'Build, mine, and explore the stars with friends without physics lag.'),
    longDescription: t('games.space_engineers.long_desc', 'Conquer the solar system. Our infrastructure utilizes advanced Wine compatibility layers to run the Windows-only Space Engineers dedicated server seamlessly on high-performance Linux hardware.'),
    image: '/games/space_engineers-bg.jpg',
    accent: 'text-purple-400',
    btnBg: 'bg-purple-600',
    btnHover: 'hover:bg-purple-700',
    engine: 'VRAGE 2.0 (Wine)'
  },
  {
    id: 'seven_days_to_die',
    name: '7 Days to Die',
    edition: t('games.seven_days_to_die.edition', 'Zombie Survival'),
    description: t('games.seven_days_to_die.desc', 'Survive the blood moon horde with native high-performance hosting.'),
    longDescription: t('games.seven_days_to_die.long_desc', 'Prepare for the 7th night. Host your own 1.0 dedicated server with fast NVMe loading times for vast voxel destruction and horde management.'),
    image: '/games/7dtd-bg.jpg',
    accent: 'text-red-500',
    btnBg: 'bg-red-600',
    btnHover: 'hover:bg-red-700',
    engine: 'Unity'
  },
  {
    id: 'conan_exiles',
    name: 'Conan Exiles',
    edition: t('games.conan_exiles.edition', 'Dedicated Server'),
    description: t('games.conan_exiles.desc', 'Survive, build, and dominate the Exiled Lands with flawless performance.'),
    longDescription: t('games.conan_exiles.long_desc', 'Crush your enemies in the Exiled Lands. Our Conan Exiles servers utilize our high-performance Wine wrapper to deliver seamless, lag-free survival combat.'),
    image: '/games/conan_exiles-bg.jpg',
    accent: 'text-amber-500',
    btnBg: 'bg-amber-600',
    btnHover: 'hover:bg-amber-700',
    engine: 'Unreal Engine 4 (Wine)'
  },
  {
    id: 'dayz',
    name: 'DayZ',
    edition: t('games.dayz.edition', 'Hardcore Survival'),
    description: t('games.dayz.desc', 'Survive the post-apocalypse with heavy modding support and high tick rates.'),
    longDescription: t('games.dayz.long_desc', 'The ultimate hardcore survival game. We support 1-click Steam Workshop installations to easily mount map overhauls like Namalsk or Deer Isle.'),
    image: '/games/dayz-bg.jpg',
    accent: 'text-emerald-500',
    btnBg: 'bg-emerald-600',
    btnHover: 'hover:bg-emerald-700',
    engine: 'Enfusion / Real Virtuality'
  },
  {
    id: 'enshrouded',
    name: 'Enshrouded',
    edition: t('games.enshrouded.edition', 'Voxel Survival'),
    description: t('games.enshrouded.desc', 'Explore a massive voxel-based continent with up to 16 players in seamless co-op.'),
    longDescription: t('games.enshrouded.long_desc', 'Host an Enshrouded server for up to 16 players. Build magnificent voxel castles and explore the shroud with our high-clock CPUs powering the backend.'),
    image: '/games/enshrouded-bg.jpg',
    accent: 'text-blue-400',
    btnBg: 'bg-blue-500',
    btnHover: 'hover:bg-blue-600',
    engine: 'Holistic Engine (Wine)'
  },
  {
    id: 'sons_of_the_forest',
    name: 'Sons of the Forest',
    edition: t('games.sons_of_the_forest.edition', 'Co-op Survival'),
    description: t('games.sons_of_the_forest.desc', 'Build and survive against mutants in a terrifying forest with zero lag.'),
    longDescription: t('games.sons_of_the_forest.long_desc', 'Host your terrifying co-op adventure. Our servers provide massive RAM allocation to handle sprawling bases and aggressive mutant AI without skipping a beat.'),
    image: '/games/sotf-bg.jpg',
    accent: 'text-green-500',
    btnBg: 'bg-green-600',
    btnHover: 'hover:bg-green-700',
    engine: 'Unity (Wine)'
  },
  {
    id: 'v_rising',
    name: 'V Rising',
    edition: t('games.v_rising.edition', 'Vampire Survival'),
    description: t('games.v_rising.desc', 'Awaken as a vampire, rebuild your castle, and rule the night with friends.'),
    longDescription: t('games.v_rising.long_desc', 'Rule Vardoran. Set up a private PvE realm or a brutal PvP server. High-performance hosting ensures your vampire combat remains sharp and responsive.'),
    image: '/games/vrising-bg.jpg',
    accent: 'text-rose-500',
    btnBg: 'bg-rose-600',
    btnHover: 'hover:bg-rose-700',
    engine: 'Unity (Wine)'
  },
  {
    id: 'core_keeper',
    name: 'Core Keeper',
    edition: t('games.core_keeper.edition', 'Mining Sandbox'),
    description: t('games.core_keeper.desc', 'Mine, build, and explore in this underground co-op adventure.'),
    longDescription: t('games.core_keeper.long_desc', 'Host a persistent underground world. Core Keeper uses minimal resources, making it a perfect, affordable server to run for your friend group 24/7.'),
    image: '/games/core_keeper-bg.jpg',
    accent: 'text-teal-400',
    btnBg: 'bg-teal-500',
    btnHover: 'hover:bg-teal-600',
    engine: 'Unity'
  },
  {
    id: 'squad',
    name: 'Squad',
    edition: t('games.squad.edition', 'Tactical FPS'),
    description: t('games.squad.desc', '50v50 tactical shooter with robust server performance for large-scale operations.'),
    longDescription: t('games.squad.long_desc', 'Power your clan\'s 100-player operations. Squad relies heavily on high-frequency processors to maintain 50 TPS. We deliver the compute power your community needs.'),
    image: '/games/squad-bg.jpg',
    accent: 'text-yellow-400',
    btnBg: 'bg-yellow-500',
    btnHover: 'hover:bg-yellow-600',
    engine: 'Unreal Engine 4'
  },
  {
    id: 'insurgency_sandstorm',
    name: 'Insurgency: Sandstorm',
    edition: t('games.insurgency_sandstorm.edition', 'Hardcore Tactical'),
    description: t('games.insurgency_sandstorm.desc', 'Intense close-quarters combat and objective-based multiplayer.'),
    longDescription: t('games.insurgency_sandstorm.long_desc', 'Host lightning-fast, high-tickrate Insurgency servers. Complete support for Steam Workshop maps and mutators right from our dashboard.'),
    image: '/games/insurgency-bg.jpg',
    accent: 'text-orange-500',
    btnBg: 'bg-orange-600',
    btnHover: 'hover:bg-orange-700',
    engine: 'Unreal Engine 4'
  },
  {
    id: 'unturned',
    name: 'Unturned',
    edition: t('games.unturned.edition', 'Zombie Sandbox'),
    description: t('games.unturned.desc', 'Free-to-play survival with a massive community and extensive mod support.'),
    longDescription: t('games.unturned.long_desc', 'Host lightweight, fast, and easily moddable Unturned servers. Perfect for large communities looking to install RocketMod and custom Steam Workshop assets.'),
    image: '/games/unturned-bg.jpg',
    accent: 'text-lime-400',
    btnBg: 'bg-lime-500',
    btnHover: 'hover:bg-lime-600',
    engine: 'Unity'
  },
  {
    id: 'tf2',
    name: 'Team Fortress 2',
    edition: t('games.tf2.edition', 'Source Engine'),
    description: t('games.tf2.desc', 'Classic class-based shooter hosting with instant FastDL integration.'),
    longDescription: t('games.tf2.long_desc', 'Keep the classic alive. Host 24/7 2Fort, Jump maps, or MGE servers with full SourceMod/MetaMod support and ultra-low latency.'),
    image: '/games/tf2-bg.jpg',
    accent: 'text-orange-500',
    btnBg: 'bg-orange-600',
    btnHover: 'hover:bg-orange-700',
    engine: 'Source'
  },
  {
    id: 'l4d2',
    name: 'Left 4 Dead 2',
    edition: t('games.l4d2.edition', 'Co-op Zombie Shooter'),
    description: t('games.l4d2.desc', 'Survive the apocalypse with seamless custom campaign and mod support.'),
    longDescription: t('games.l4d2.long_desc', 'Host 8-player Versus or 4-player Co-op. Fully supports Steam Workshop custom campaigns and SourceMod for intense, heavily modified director AI.'),
    image: '/games/l4d2-bg.jpg',
    accent: 'text-red-500',
    btnBg: 'bg-red-600',
    btnHover: 'hover:bg-red-700',
    engine: 'Source'
  },
  {
    id: 'dst',
    name: "Don't Starve Together",
    edition: t('games.dst.edition', 'Wilderness Survival'),
    description: t('games.dst.desc', 'Uncompromising wilderness survival game full of science and magic.'),
    longDescription: t('games.dst.long_desc', 'Survive together. DST servers are incredibly lightweight, meaning you can host massive mega-worlds for your friends at a fraction of the cost.'),
    image: '/games/dst-bg.jpg',
    accent: 'text-amber-400',
    btnBg: 'bg-amber-500',
    btnHover: 'hover:bg-amber-600',
    engine: 'Klei Engine'
  },
  {
    id: 'terraria',
    name: 'Terraria',
    edition: t('games.terraria.edition', 'Vanilla & TShock'),
    description: t('games.terraria.desc', 'Dig, fight, explore, and build with robust plugin support.'),
    longDescription: t('games.terraria.long_desc', 'Host cross-platform Terraria servers using TShock. Gain full admin control, world protection, and massive multiplayer support on our lightweight instances.'),
    image: '/games/terraria-bg.jpg',
    accent: 'text-emerald-400',
    btnBg: 'bg-emerald-500',
    btnHover: 'hover:bg-emerald-600',
    engine: 'XNA (Mono)'
  },
  {
    id: 'stardew_valley',
    name: 'Stardew Valley',
    edition: t('games.stardew_valley.edition', 'Co-op Farming'),
    description: t('games.stardew_valley.desc', 'Farm, forage, and build a community with seamless multiplayer hosting.'),
    longDescription: t('games.stardew_valley.long_desc', 'Host a persistent 24/7 farm for you and your friends. We utilize open-source headless wrappers to keep your Stardew Valley world alive even when you log off.'),
    image: '/games/stardew-bg.jpg',
    accent: 'text-pink-400',
    btnBg: 'bg-pink-500',
    btnHover: 'hover:bg-pink-600',
    engine: 'XNA (Mono)'
  }
];