// pages/privacy.js
import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Link from "next/link";
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'; // <--- IMPORTED

export default function PrivacyPolicy() {
  const lastUpdated = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return (
    <div className="min-h-screen flex flex-col bg-gray-50 dark:bg-slate-950 font-sans text-slate-900 dark:text-slate-100 transition-colors duration-300">
      <Head>
        <title>Privacy Policy | Spawnly</title>
      </Head>

      <Navbar />

      <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="max-w-4xl mx-auto bg-white dark:bg-slate-800 p-8 rounded-2xl shadow-sm border border-gray-100 dark:border-slate-700">
          
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">Privacy Policy</h1>
          <p className="text-gray-500 dark:text-gray-400 mb-8">Last Updated: {lastUpdated}</p>

          <div className="prose prose-slate dark:prose-invert max-w-none text-gray-700 dark:text-gray-300 space-y-6">
            
            <section>
              <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">1. Introduction</h2>
              <p>
                Welcome to <strong>Spawnly</strong> ("we," "our," or "us"). We are committed to protecting your personal information and your right to privacy. 
                This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our website and hosting services.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">2. Data Controller</h2>
              <p>
                For the purposes of the GDPR, the data controller is:<br/>
                <strong>[YOUR COMPANY NAME]</strong><br/>
                [YOUR FULL ADDRESS]<br/>
                Portugal<br/>
                Email: <a href="mailto:support@spawnly.net" className="text-indigo-600 hover:underline">support@spawnly.net</a>
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">3. Information We Collect</h2>
              <ul className="list-disc pl-5 space-y-2">
                <li>
                  <strong>Account Information:</strong> Email address, User ID (via OAuth providers), and billing history.
                </li>
                <li>
                  <strong>Server Data:</strong> World files, configuration files, and logs generated by your server instances.
                </li>
                <li>
                  <strong>Usage Data:</strong> Timestamps of server starts/stops and resource consumption (RAM/CPU) for billing purposes.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">4. Third-Party Processors</h2>
              <p>We share data with the following sub-processors to provide the service:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li><strong>Hetzner Online GmbH (Germany):</strong> Hosting infrastructure.</li>
                <li><strong>Supabase Inc (AWS):</strong> Database and Authentication.</li>
                <li><strong>Stripe (Global):</strong> Payment processing.</li>
                <li><strong>Google (Global):</strong> Social login authentication.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">5. Data Retention & Deletion</h2>
              <p>
                We retain your data as long as your account is active. 
                Server files are retained for the duration of your server's existence. 
                Upon deleting a server in the dashboard, the associated S3 data is permanently removed immediately.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-3">6. Contact</h2>
              <p>
                To exercise your GDPR rights (Access, Rectification, Erasure), please contact us at:
              </p>
              <div className="mt-4 p-4 bg-gray-50 dark:bg-slate-700/50 rounded-lg border border-gray-200 dark:border-slate-600 inline-block">
                <p className="font-medium text-indigo-600 dark:text-indigo-400">support@spawnly.net</p>
              </div>
            </section>

          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}

// --- REQUIRED FOR NAVBAR/FOOTER TRANSLATIONS ---
export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
    },
  };
}